# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [19]:
import numpy as np
Arr = np.arange(11).reshape(1, 11)
Arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [20]:
for val in range(3, 7):
    Arr[0, val] = -Arr[0, val]
Arr    

array([[ 0,  1,  2, -3, -4, -5, -6,  7,  8,  9, 10]])

### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [22]:
A = np.random.rand(3, 6)
print(A)
B = A[ A > 0.5 ]
B.size

[[0.66379566 0.52201509 0.55326766 0.79372325 0.10507876 0.64407663]
 [0.37540391 0.29710847 0.07551704 0.847817   0.11753037 0.79053386]
 [0.78471391 0.89383413 0.22658855 0.68681537 0.11677302 0.47480117]]


10