# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [10]:
import numpy as np 

a = np.arange(6)
print(a)
print(a.sum())
print(a.sum().dtype)
print(a)
print(np.sum(a))
print(np.sum(a).dtype)
print(a)
print(sum(a)) 
print(sum(a).dtype)

[0 1 2 3 4 5]
15
int64
[0 1 2 3 4 5]
15
int64
[0 1 2 3 4 5]
15
int64


以上得到相同的結果

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [12]:
import numpy as np 

In [16]:
A = np.random.random((5, 5))
print(A)
def normalization(data):
    _range = np.max(data) - np.min(data)
    return (data - np.min(data)) / _range
normalization(A)

[[0.18784944 0.27177912 0.7235549  0.87149257 0.44809117]
 [0.38729497 0.5115661  0.03566111 0.27598659 0.91857439]
 [0.56400029 0.94688634 0.81601296 0.88597772 0.40944753]
 [0.01499151 0.52414822 0.52653557 0.53584331 0.62224292]
 [0.37150761 0.47163998 0.65494715 0.33882007 0.53480803]]


array([[0.18549081, 0.27555428, 0.76034695, 0.91909626, 0.46475165],
       [0.39951232, 0.53286548, 0.02218018, 0.28006924, 0.96961894],
       [0.58913169, 1.        , 0.85956207, 0.93464003, 0.42328384],
       [0.        , 0.54636713, 0.54892896, 0.55891694, 0.65163084],
       [0.38257117, 0.49002146, 0.68672517, 0.34749475, 0.55780599]])

### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [51]:
import random
Vec = np.random.randint(1, 100, 10) 
print('Vector = ', Vec)
print('Max = ', Vec[Vec.argmax()])
Vec[Vec.argmax()] = -1
print(Vec)

Vector =  [30 89 60 61 94 65 40 19 29 51]
Max =  94
[30 89 60 61 -1 65 40 19 29 51]
